# -*- coding: utf-8 -*-
"""Amazon_Laptops

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dasnS0auz5EzV_z8g7Q8kGmuNMvXgF-m
"""

# Importing libraries
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import csv

pages = np.arange(1,4,1)

# User defined functions

def get_title(soup):
    
    try:
        title = soup.find('span',attrs={'id':'productTitle'})
        title_value = title.text
        title_string = title_value.strip()
    except AttributeError:
        title_string = ''
    return title_string

def get_price(soup):
    try:
        price = soup.find('span',attrs={'class':'a-price-whole'})
        price_value = price.text
        price_str = price_value.strip()
    except AttributeError:
        price_str =''
    return price_str


def get_rating(soup):
    try:
        rating = soup.find('span',attrs={'class':'a-icon-alt'})
        rating_value = rating.text
        rating_str = rating_value.strip()
    except AttributeError:
        rating_str =''
    return rating_str



def get_nrating(soup):
    try:
        nrating = soup.find('span',attrs={'id':'acrCustomerReviewText'})
        nrating_value = nrating.text
        nrating_str = nrating_value.strip()
    except AttributeError:
        nrating_str =''
    return nrating_str




def get_brand(soup):
    try:
        brand = soup.find('tr',attrs = {'class':'a-spacing-small po-brand'})
        brand_value = brand.text
        brand_real = brand_value.replace('Brand   ','')
        brand_str = brand_value.strip()
    except AttributeError:
        brand_str = ''
    return brand_str


def get_model(soup):
    try:
        model = soup.find('tr',attrs = {'class':'a-spacing-small po-model_name'})
        model_value = model.text
        model_real = model_value.replace('Model Name   ','')
        model_str = model_real.strip()
    except AttributeError:
        model_str = ''
    return model_str


def get_screen(soup):
    try:
        model = soup.find('tr',attrs = {'class':'a-spacing-small po-display.size'})
        screen_value = model.text
        screen_real = screen_value.replace('Screen Size   ','')
        screen_str = screen_real.strip()
    except AttributeError:
        screen_str = ''
    return screen_str


def get_colour(soup):
    try:
        model = soup.find('tr',attrs = {'class':'a-spacing-small po-color'})
        colour_value = model.text
        colour_real = colour_value.replace('Colour   ','')
        colour_str = colour_real.strip()
    except AttributeError:
        colour_str = ''
    return colour_str


def get_cpu(soup):
    try:
        model = soup.find('tr',attrs = {'class':'a-spacing-small po-cpu_model.family'})
        cpu_value = model.text
        cpu_real = cpu_value.replace('CPU Model   ','')
        
        
        cpu_str = cpu_real.strip()
    except AttributeError:
        cpu_str = ''
    return cpu_str


def get_RAM(soup):
    try:
        model = soup.find('tr',attrs = {'class':'a-spacing-small po-ram_memory.installed_size'})
        RAM_value = model.text
        RAM_real = RAM_value.replace('RAM Memory Installed Size   ','')
        RAM_str = RAM_real.strip()
    except AttributeError:
        RAM_str = ''
    return RAM_str


def get_OS(soup):
    try:
        model = soup.find('tr',attrs = {'class':'a-spacing-small po-operating_system'})
        OS_value = model.text
        OS_real = OS_value.replace('Operating System   ','')
        OS_str = OS_real.strip()
    except AttributeError:
        OS_str = ''
    return OS_str



def get_SF(soup):
    try:
        model = soup.find('tr',attrs = {'class':'a-spacing-small po-special_feature'})
        SF_value = model.text
        SF_real = SF_value.replace('Special Feature   ','')
        SF_str = SF_real.strip()
    except AttributeError:
        SF_str = ''
    return SF_str


def get_graphics(soup):
    try:
        model = soup.find('tr',attrs = {'class':'a-spacing-small po-graphics_description'})
        graphics_value = model.text
        graphics_real = graphics_value.replace('Graphics Card Description   ','')
        graphics_str = graphics_real.strip()
    except AttributeError:
        graphics_str = ''
    return graphics_str


def get_graphicsCo(soup):
    try:
        model = soup.find('tr',attrs = {'class':'a-spacing-small po-graphics_coprocessor'})
        graphicsCo_value = model.text
        graphicsCo_real = graphicsCo_value.replace('Graphics Coprocessor   ','')
        graphicsCo_str = graphicsCo_real.strip()
    except AttributeError:
        graphicsCo_str = ''
    return graphicsCo_str

# From getting data to creating dataframe

if __name__ == '__main__':
  for req in pages:
    Headers = ({'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36', 'Accept-Language':'en-US, en;q=0.5'})
    
    req = requests.get('https://www.amazon.in/s?k=laptops&i=computers&rh=n%3A1375424031&page='+str(req)+'&qid=1675012650&ref=sr_pg_'+str(req), headers = Headers)
    soup = BeautifulSoup(req.content, 'html.parser')
    links = soup.find_all('a', attrs = {'class': 'a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal'})
    links_list = []
    for link in links:
        links_list.append(link.get('href'))
        
    d = {'title':[], 'price':[], 'rating':[], 'no_of_rating':[], 'brand':[], 'model':[], 'screen':[], 'colour':[], 'cpu':[], 'RAM_size':[], 'Operating_system':[], 'Special_feature':[], 'graphics_card_description':[], 'graphics_coprocessor':[]}
    for link in links_list:
        new_web = requests.get('https://www.amazon.in'+link, headers=Headers)
        new_soup = BeautifulSoup(new_web.content, 'html.parser')
        
        
        d['title'].append(get_title(new_soup))
        d['price'].append(get_price(new_soup))
        d['rating'].append(get_rating(new_soup))
        d['no_of_rating'].append(get_nrating(new_soup))
        d['brand'].append(get_brand(new_soup))
        d['model'].append(get_model(new_soup))
        d['screen'].append(get_screen(new_soup))
        d['colour'].append(get_colour(new_soup))
        d['cpu'].append(get_cpu(new_soup))
        d['RAM_size'].append(get_RAM(new_soup))
        d['Operating_system'].append(get_OS(new_soup))
        d['Special_feature'].append(get_SF(new_soup))
        d['graphics_card_description'].append(get_graphics(new_soup))
        d['graphics_coprocessor'].append(get_graphicsCo(new_soup))
        
    adf = pd.DataFrame.from_dict(d)

# Dataframe
adf

# json format
js = adf.to_json('laptop.json')

